FROM python:3.12-slim
RUN pip install poetry==2.1.3
WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false
RUN poetry install
COPY ./ .
WORKDIR /app/src
CMD ["faststream", "run", "emulator:app"]