"""create outboxMessage

Revision ID: 260e82357bd5
Revises: 9d7d42f8a29c
Create Date: 2026-04-23 19:51:57.340492

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '260e82357bd5'
down_revision: Union[str, Sequence[str], None] = '9d7d42f8a29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outboxmessage',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'event_type', sa.String(
                            length=200), nullable=True),
                    sa.Column('payload', sa.JSON(), nullable=True),
                    sa.Column(
                        'status',
                        sa.Enum(
                            'PENDING',
                            'SENT',
                            'FAILED',
                            name='outboxstatus'),
                        nullable=False),
                    sa.Column('attempts', sa.Integer(), nullable=False),
                    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outboxmessage')
    # ### end Alembic commands ###
