"""First migration

Revision ID: 39a23b955f9f
Revises:
Create Date: 2026-04-22 11:46:48.824580

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '39a23b955f9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'amount',
                        sa.Numeric(
                            precision=10,
                            scale=2),
                        nullable=True),
                    sa.Column('currency', sa.String(length=3), nullable=True),
                    sa.Column(
                        'description', sa.String(
                            length=255), nullable=True),
                    sa.Column('metadata_', sa.JSON(), nullable=True),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column(
                        'idempotency_key', sa.String(
                            length=64), nullable=True),
                    sa.Column(
                        'webhook_url', sa.String(
                            length=512), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('processed_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_payment_idempotency_key'),
        'payment',
        ['idempotency_key'],
        unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_idempotency_key'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
