"""change field OutBoxMessage

Revision ID: 443f2e13c37b
Revises: edfcc051b469
Create Date: 2026-04-23 22:01:26.827529

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '443f2e13c37b'
down_revision: Union[str, Sequence[str], None] = 'edfcc051b469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'outboxmessage',
        sa.Column(
            'idempotency_key',
            sa.String(200),
            nullable=False))
    op.create_index(
        op.f('ix_outboxmessage_idempotency_key'),
        'outboxmessage',
        ['idempotency_key'],
        unique=False)
    op.drop_column('outboxmessage', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'outboxmessage',
        sa.Column(
            'id',
            sa.INTEGER(),
            autoincrement=True,
            nullable=False))
    op.drop_index(
        op.f('ix_outboxmessage_idempotency_key'),
        table_name='outboxmessage')
    op.drop_column('outboxmessage', 'idempotency_key')
    # ### end Alembic commands ###
