"""change field webhook

Revision ID: 9d7d42f8a29c
Revises: b62aac458759
Create Date: 2026-04-23 09:17:00.472054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7d42f8a29c'
down_revision: Union[str, Sequence[str], None] = 'b62aac458759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'webhook_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'webhook_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###
