"""outboxMessage change date fields next attemp

Revision ID: edfcc051b469
Revises: 320dff1d45f6
Create Date: 2026-04-23 20:11:20.679240

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'edfcc051b469'
down_revision: Union[str, Sequence[str], None] = '320dff1d45f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outboxmessage', 'next_attempt_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.TIMESTAMP(timezone=True),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outboxmessage', 'next_attempt_at',
                    existing_type=sa.TIMESTAMP(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    # ### end Alembic commands ###
